













###for a simple signup
POST http://localhost:8000/api/signup/
Content-Type: application/json

{
  "username": "reda",
  "first_name": "Reda",
  "last_name": "Bouissali",
  "email": "reda@example.com",
  "password": "123"
}



###for a simple login
POST http://localhost:8000/api/login/
Content-Type: application/json

{
  "username": "reda",
  "password": "123"
}


###
PUT http://localhost:8000/api/user/change_password/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2Njg2NjExLCJpYXQiOjE3NjY2ODMwMTEsImp0aSI6IjBjYzY1OGJjMDRjNjQzMDhhZDA4Y2JlNmJiZWI2OGNjIiwidXNlcl9pZCI6IjEifQ.oCn43tT8oX9x0R_kPgxTZFAD33dUt-OmunBhojUcr2c
Content-Type: application/json

{
  "password": "123",
  "new_password": "newStrongPassword123"
}


