





#this two working proprely perfect 
###
GET  http://localhost:8000/api/um6p/latest/
Accept: application/json



###
GET  http://localhost:8000/api/marrakech/latest/
Accept: application/json



###for airgridient
GET  http://localhost:8000/api/pergola_um6p/air_latest/
Accept: application/json

###
GET http://localhost:8000/api/pergola_um6p/airgradient/last24h/


###
GET http://localhost:8000/api/marrakech/airgradient/last7d/




