# Generated by Django 5.0.1 on 2026-01-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
